local NO_01 = {
 Information = {
  Index = 1001,
  Ename = "NO_01",
  Name = '小兔子',
  Description = '',
  Cost = 25,
  MaxStar = 5,
  Profession = 'DPS',
  Sex = "Male",
 },
Skeleton = {
  name = "honghaier",
  actions = {
  idle = {"idle", 40},
  run = {"run", 24},
  victory = {"victory", 24},
  death = {"death", 43},
  smitten = {"smitten", 22},
  normalatkQian = {"normalatkQian", 26},
  normalatkHou = {"normalatkHou", 20},
  superatkQian = {"superatkQian", 18},
  superatkHou = {"superatkHou", 79},
  normalDandao = 8,
  superDandao = 76,
  },
 },
 Ability = {
  BaseAtk = 10,
  BaseMiss = 5,
  DeltaMiss = 0,
  DeltaAtk = 7, 
  BaseDef = 20, 
  DeltaDef = 2, 
  BaseHp = 300, 
  DeltaHp = 40, 
  MoveFriend = 9999,
  MoveEnemy = 0, 
  MovePreference = 0, 
 },
 Resistance = {
  Stun = 0,
  Freeze = 0,
  Disarm = 0,
  Poison = 0,
  Bleeding = 0,
  CriticalDamage = 0,
 },
 NormalAtk = {
  Name = '挠',
  Description = '',
  Range = {{-1,0},},
  HitType = "ground",
  Speed = 20,
  HitPerBox = 1,
  CriP = 0,
  CriV = 0,
  ReceiverIsFriend = false,
  EffectToR = {
   Type = 1,
   BaseNumber = 100,
   DeltaNumber = 0, 
   Special = 0, 
   Buffs = {  
    -- Atk = {
    --  BaseTime = 3,
    --  DeltaTime = 0,
    --  BaseNumber = -130,
    --  DeltaNumber = 0,
    --  BaseSuccess = 100,
    --  DeltaSuccess = 0,
    --  IsGoodBuff = false,
    --  },
   },
  },
  EffectToC = {
   Type = 0, 
   BaseNumber = 0, 
   DeltaNumber = 0, 
   Buffs = {
    Hp = {
     BaseTime = 3,
     DeltaTime = 0,
     BaseNumber = 130,
     DeltaNumber = 0,
     BaseSuccess = 100,
     DeltaSuccess = 0,
     IsGoodBuff = true,
    },
   },
  },
 },
 SuperAtk = {
 },
 LeaderSkill = {
 },
 CooperateSkill = {},
}

return NO_01